### ISSUE TITLE
Não mostrar texto

### ISSUE THREAD

**Issue by Gatelica** [KcNirvana/HyperOS-XML-1.0-Portuguese#2]
Olá boa tarde, notei que a opção de **Não mostrar texto** em (Ecrã inicial > Configurações da tela inicial) não funciona corretamente nas definições com este idioma em específico: Português (Portugal), não sendo possível controlar as 3 opções "Desligado, Em todo o lado, Em widgets".

![screenshot_2](https://github.com/KcNirvana/HyperOS-XML-1.0-Portuguese/assets/154292108/478380a2-06c2-42f3-9605-ddb92822a9e4)

xiaomi.eu_multi_MOONSTONE_OS1.0.3.0.UMPMIXM_os1-14
xiaomi.eu_multi_REDWOOD_OS1.0.4.0.UMSCNXM_os1-14

**Comment by KcNirvana** [comment]
Boa tarde,
Pode mandar um print do mesmo ecrã mas em EN-US?
Obrigado.

**Comment by Gatelica** [comment]
> Boa tarde, Pode mandar um print do mesmo ecrã mas em EN-US? Obrigado.

![pic4](https://github.com/KcNirvana/HyperOS-XML-1.0-Portuguese/assets/154292108/d516a24c-26b5-4239-a95c-4d950996dce4)
